import { tfs } from "../strings";

export const serverRole = (role: string): string => role === "owner"
  ? tfs("ui.staff.role_owner") : role === "staff"
  ? tfs("ui.staff.role_staff") : role === "player" || !role
  ? tfs("ui.staff.role_player") : role;

export const TITLE = tfs("ui.staff.title");
export const LIVE = tfs("ui.staff.live_station");
export const CASES = tfs("ui.staff.cases");
export const PERSPECTIVE = tfs("ui.staff.perspective");
export const SERVER_GRANTED = tfs("ui.staff.server_granted");
export const EXIT = tfs("ui.staff.exit");
export const ENTER = tfs("ui.staff.enter");
export const RUNNING = tfs("ui.staff.running");
export const INSPECT = tfs("ui.staff.inspect");
export const SELECT_TARGET = tfs("ui.staff.select_target");
export const PICK_TARGET = tfs("ui.staff.pick_target");
export const LIVE_CANVAS = tfs("ui.staff.live_canvas");
export const CANVAS_HINT = tfs("ui.staff.canvas_hint");
export const ENTITIES = tfs("ui.staff.entities");
export const NO_ENTITIES = tfs("ui.staff.no_entities");
export const DECK = tfs("ui.staff.deck");
export const FOLLOW = tfs("ui.staff.follow");
export const SPAWN = tfs("ui.staff.spawn");
export const SPAWN_DRAWER = tfs("ui.staff.spawn_drawer");
export const PREPARE = tfs("ui.staff.prepare_spawn");
export const PROTOTYPE = tfs("ui.staff.prototype");
export const KIND = tfs("ui.staff.kind");
export const SEARCH = tfs("ui.staff.search_catalog");
export const LOAD_MORE = tfs("ui.staff.load_more_catalog");
export const CATALOG_LOADING = tfs("ui.staff.catalog_loading");
export const CATALOG_EMPTY = tfs("ui.staff.catalog_empty");
export const CATALOG_LIMIT = tfs("ui.staff.catalog_limit");
export const CATALOG_ERROR = (reason: string): string => tfs("ui.staff.catalog_error", { reason });
export const KIND_ITEM = tfs("ui.staff.kind_item");
export const KIND_STRUCTURE = tfs("ui.staff.kind_structure");
export const KIND_MACHINE = tfs("ui.staff.kind_machine");
export const KIND_MOB = tfs("ui.staff.kind_mob");
export const KIND_BODY = tfs("ui.staff.kind_body");
export const X = tfs("ui.staff.x");
export const Y = tfs("ui.staff.y");
export const Z = tfs("ui.staff.z");
export const PREVIEW = tfs("ui.staff.preview");
export const PLACE = tfs("ui.staff.place");
export const CANCEL = tfs("ui.staff.cancel");
export const INSPECTOR = tfs("ui.staff.inspector");
export const READ = tfs("ui.staff.read");
export const EDIT = tfs("ui.staff.edit");
export const AUDIT = tfs("ui.staff.audit");
export const INTERVENE = tfs("ui.staff.intervene");
export const FREEZE = tfs("ui.staff.freeze");
export const UNFREEZE = tfs("ui.staff.unfreeze");
export const RESTORE = tfs("ui.staff.restore");
export const DRIVE = tfs("ui.staff.drive");
export const RELEASE = tfs("ui.staff.release");
export const MOVE = tfs("ui.staff.move");
export const DUPLICATE = tfs("ui.staff.duplicate");
export const KILL = tfs("ui.staff.kill");
export const DELETE = tfs("ui.staff.delete");
export const GIB = tfs("ui.staff.gib");
export const PROPERTIES = tfs("ui.staff.properties");
export const CURRENT = tfs("ui.staff.current");
export const READ_ONLY = tfs("ui.staff.read_only");
export const APPLY = tfs("ui.staff.apply");
export const APPLY_CHANGES = (count: number): string => tfs("ui.staff.apply_changes", { count });
export const RELATED = tfs("ui.staff.related");
export const GLOBAL_AUDIT = tfs("ui.staff.global_audit");
export const NO_AUDIT = tfs("ui.staff.no_audit");
export const OPEN_CASES = tfs("ui.staff.open_cases");
export const CASE_CONTEXT = tfs("ui.staff.case_context");
export const ATTACH = tfs("ui.staff.attach");
export const CREATE_CASE = tfs("ui.staff.create_case");
export const ACTOR = tfs("ui.staff.actor");
export const MIND = tfs("ui.staff.mind");
export const BODY = tfs("ui.staff.body");
export const OPERATOR = tfs("ui.staff.operator");
export const ADMIN = tfs("ui.staff.admin");
export const RESULT = tfs("ui.staff.result");
export const HISTORY = tfs("ui.staff.history");
export const RECORDS = tfs("ui.staff.records");
export const ASSOCIATED = tfs("ui.staff.associated");
export const ALL_RECORDS = tfs("ui.staff.all_records");
export const ONLY_RECORD = tfs("ui.staff.only_record");
export const OUTCOME = tfs("ui.staff.outcome");
export const WARNINGS = tfs("ui.staff.warnings");
export const MESSAGES = tfs("ui.staff.messages");
export const REFRESH_MESSAGES = tfs("ui.staff.refresh_messages");
export const ADD_WARNING = tfs("ui.staff.add_warning");
export const SAVE_NOTE = tfs("ui.staff.save_note");
export const START_CONVERSATION = tfs("ui.staff.start_conversation");
export const SEND_MESSAGE = tfs("ui.staff.send_message");
export const NO_ACCESS = tfs("ui.staff.no_access");
export const NO_CONTROLS = tfs("ui.staff.no_controls");
export const DISCONNECTED = tfs("ui.staff.disconnected");
export const OPEN_PROFILE = tfs("ui.staff.open_profile");
export const ACCOUNT_PROFILE = tfs("ui.staff.account_profile");
export const GRANT_STAFF = tfs("ui.staff.grant_staff");
export const REVOKE_STAFF = tfs("ui.staff.revoke_staff");
export const NO_ACCOUNT = tfs("ui.staff.no_account");
export const NO_PROPERTIES = tfs("ui.staff.no_properties");
export const NO_PROPOSED = tfs("ui.staff.no_proposed");
export const EXACT_TARGET = (name: string, id: string): string => tfs("ui.staff.exact_target_detail", { name, id });
export const EXACT_TARGET_ACTIONS = tfs("ui.staff.exact_target_actions");
export const KEEP_TARGET = tfs("ui.staff.keep_target");
export const CONFIRM = tfs("ui.staff.confirm");
export const FALSE = tfs("ui.staff.false");
export const TRUE = tfs("ui.staff.true");
export const STATE = tfs("ui.staff.state");
export const LOCATION = tfs("ui.staff.location");
export const STATUS = tfs("ui.staff.status");
export const TOGGLE_INSPECTOR = tfs("ui.staff.toggle_inspector");
export const CLOSE_INSPECTOR = tfs("ui.staff.close_inspector");
export const SELECTED = (id: string): string => tfs("ui.staff.selected", { id });
export const SPAWN_PROPERTIES = tfs("ui.staff.spawn_properties");
export const PREVIEW_ACTIVE = tfs("ui.staff.preview_active");
export const NO_TARGET = tfs("ui.staff.no_target");
export const DELETED = tfs("ui.staff.deleted");
export const TOMBSTONE = tfs("ui.staff.tombstone");
export const TIME = tfs("ui.staff.time");
export const ACTION_TARGET = tfs("ui.staff.action_target");
export const ACTOR_MIND = tfs("ui.staff.actor_mind");
export const INCLUSION = tfs("ui.staff.inclusion");
export const NO_HISTORY = tfs("ui.staff.no_history");
export const CONTACT = tfs("ui.staff.contact");
export const CONTACT_NOTE = tfs("ui.staff.contact_note");
export const RECORD_ONLY = tfs("ui.staff.record_only");
export const OPEN_CASE = tfs("ui.staff.open_case");
export const CASE_STATUS = (value: string): string => tfs("ui.staff.case_status", { value });
export const SHIFT = tfs("ui.staff.shift");
export const STATION = tfs("ui.staff.station");
export const HOLD = tfs("ui.staff.hold");
export const REVISION = (value: string | number): string => tfs("ui.staff.revision", { value });
export const TARGET_COUNT = (count: number): string => tfs("ui.staff.live_target_count", { count });
export const RECORD_COUNT = (shown: number, total: number): string => tfs("ui.staff.record_count", { shown, total });
export const SOURCE_ROWS = (count: number): string => tfs("ui.staff.source_rows", { count });
export const RELATED_THROUGH = (target: string): string => tfs("ui.staff.related_through", { target });
export const EXACT_EVENT = tfs("ui.staff.exact_event");
export const ANCHOR_HISTORY = tfs("ui.staff.anchor_history");
export const CHOOSE_CASE = tfs("ui.staff.choose_case");
export const EMPTY_FILTER = tfs("ui.staff.empty_filter");
export const NO_CASE = tfs("ui.staff.no_case");
export const NO_RECORDS = tfs("ui.staff.no_records");
export const INSPECT_HINT = tfs("ui.staff.inspect_hint");
export const OUTCOME_NOTE = tfs("ui.staff.outcome_note");
export const OUTCOME_LABEL = tfs("ui.staff.outcome_label");
export const DURATION = tfs("ui.staff.duration");
export const OPERATOR_REASON = tfs("ui.staff.operator_reason");
export const SAVE_OUTCOME = tfs("ui.staff.save_outcome");
export const KILL_EFFECT = tfs("ui.staff.kill_effect");
export const GIB_EFFECT = tfs("ui.staff.gib_effect");
export const DELETE_EFFECT = tfs("ui.staff.delete_effect");
export const REVIEW_KILL = tfs("ui.staff.review_kill");
export const REVIEW_DELETE = tfs("ui.staff.review_delete");
export const REVIEW_GIB = tfs("ui.staff.review_gib");

export const REQUEST_FAILED = (reason: string): string => tfs("ui.staff.request_failed", { reason });
export const RESTORE_APPLIED = tfs("ui.staff.restore_applied");
export const RESTORE_PARTIAL = (reason: string): string => tfs("ui.staff.restore_partial", { reason });
