import type { UiStyleRule } from "@lunatic/ui";
import { defineStyles, rule } from "@lunatic/ui";
import { kitRules } from "./kit";
import { edge, flat, insetLine, none, press } from "./parts";
import { alpha, amber, bright, dim, face, faceLine, faint, field, ink, line, red, redLine, ruleLine, screen, surface, teal } from "./tokens";

/** BWOINK staff shell: a map-first intervention surface and evidence desk. */
export const staffRules: UiStyleRule[] = [
  // The inspector and case panes own their bounded scroll surfaces.
  rule("window-body", { overflow: "hidden" }),
  rule("staff-shell", {
    width: "100%", height: "100%", minHeight: 0, padding: 0, gap: 0,
    backgroundColor: "transparent", color: bright, fontFamily: "sans", fontSize: 13,
    overflow: "hidden", pointerEvents: "none", border: none, boxShadow: flat,
  }),
  // Screen keeps this toolbar outside its one body scroller, so the account
  // header and the two destinations stay pinned over the running canvas.
  rule("toolbar", {
    flexShrink: 0, minHeight: 0, padding: 0, gap: 0, flexDirection: "column",
    alignItems: "stretch", backgroundColor: "transparent", border: none, pointerEvents: "auto",
  }, { within: "staff-shell" }),
  rule("staff-header", { width: "100%", height: 80, minHeight: 80, maxHeight: 80, flexShrink: 0, padding: 16, backgroundColor: field, borderBottom: edge(ruleLine), pointerEvents: "auto" }),
  rule("staff-brand", { color: bright, fontFamily: "sans", fontSize: 16, fontWeight: "bold", letterSpacing: 1, lineHeight: 1.05, whiteSpace: "pre-wrap", textTransform: "uppercase", flexShrink: 0 }),
  rule("staff-header-perspective", { flexGrow: 1, minWidth: 0, gap: 2, overflow: "hidden" }),
  rule("staff-header-perspective-label", { color: faint, fontFamily: "mono", fontSize: 10, letterSpacing: 1, textTransform: "uppercase", whiteSpace: "nowrap" }),
  rule("staff-header-perspective-value", { minWidth: 0, color: bright, fontFamily: "sans", fontSize: 13, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }),
  rule("staff-header-profile", { flexDirection: "row", alignItems: "center", flexShrink: 0, minHeight: 48 }),
  rule("staff-card-action-label", { display: "none" }, { within: "staff-header-profile" }),
  rule("staff-status-bar", { width: "100%", height: 36, minHeight: 36, maxHeight: 36, flexShrink: 0, padding: 8, paddingLeft: 16, paddingRight: 16, backgroundColor: alpha(surface, 0.8), borderBottom: edge(ruleLine), pointerEvents: "auto" }),
  rule("staff-workspace-tabs", { width: "100%", height: 44, minHeight: 44, maxHeight: 44, flexShrink: 0, padding: 0, backgroundColor: alpha(surface, 0.96), borderBottom: edge(ruleLine), pointerEvents: "auto" }),
  rule("staff-workspace-nav", { width: "100%", height: 44, minHeight: 44, gap: 0, alignItems: "stretch", pointerEvents: "auto" }),
  rule("staff-workspace-tab", { height: 44, minHeight: 44, paddingLeft: 16, paddingRight: 16, color: dim, backgroundColor: "transparent", border: none, borderRadius: 0, fontFamily: "sans", fontSize: 12, justifyContent: "center" }),
  rule("staff-workspace-tab-selected", { color: teal, backgroundColor: "transparent", boxShadow: insetLine("bottom", teal) }),
  rule("staff-tabs", { flexShrink: 0, gap: 2 }),
  rule("btn", { minHeight: 34 }, { within: "staff-shell" }),
  rule("btn-primary", { color: teal, backgroundColor: alpha(teal, 0.1), border: edge(teal) }, { within: "staff-shell" }),
  rule("btn-danger", { color: red, border: edge(red) }, { within: "staff-shell" }),
  rule("tab", { fontFamily: "sans", fontSize: 12 }, { within: "staff-shell" }),
  rule("tab-on", { color: teal, backgroundColor: "transparent", outline: none, boxShadow: insetLine("bottom", teal) }, { within: "staff-shell" }),
  // The world/case layouts own their bounded panes. The Screen body itself
  // must not form a second wheel target over the game's canvas.
  rule("scroll", { flexGrow: 1, minWidth: 0, minHeight: 0, padding: 0, gap: 0, overflowX: "hidden", overflowY: "hidden", pointerEvents: "none" }, { within: "staff-shell" }),
  rule("staff-live-layout", { display: "flex", flexGrow: 1, minWidth: 0, minHeight: 0, gap: 7, alignItems: "stretch", pointerEvents: "none" }),
  rule("staff-live-stage", { flexGrow: 1, minWidth: 0, minHeight: 0, gap: 7, pointerEvents: "none", backgroundColor: "transparent" }),
  rule("staff-world-heading", { minHeight: 45, flexShrink: 0 }),
  rule("staff-world-title", { minWidth: 0, flexGrow: 1, gap: 2 }),
  rule("staff-live-mark", { width: 9, height: 9, flexShrink: 0, backgroundColor: teal, borderRadius: 5, boxShadow: [{ x: 0, y: 0, blur: 0, spread: 3, color: alpha(teal, 0.22) }] }),
  rule("staff-title", { color: bright, fontSize: 17, fontWeight: "bold", letterSpacing: 1 }),
  rule("staff-stage-selection", { color: bright, fontSize: 13, fontWeight: "bold" }),
  rule("staff-section-title", { color: bright, fontSize: 14, fontWeight: "bold" }),
  rule("staff-eyebrow", { color: dim, fontFamily: "mono", fontSize: 10, textTransform: "uppercase", letterSpacing: 1 }),
  rule("staff-muted", { color: dim, fontSize: 11 }),
  rule("staff-mono", { color: faint, fontFamily: "mono", fontSize: 10 }),
  rule("staff-good", { color: teal, fontWeight: "bold" }),
  rule("staff-warning", { color: amber, fontWeight: "bold" }),
  rule("staff-toolbar", { minHeight: 34, padding: 4, backgroundColor: alpha(face, 0.65), border: edge(faceLine), flexWrap: "wrap" }),
  rule("staff-deck", { flexGrow: 0, width: 105, minWidth: 90 }),
  rule("staff-stage-status", { minHeight: 28, padding: 5, backgroundColor: alpha(surface, 0.82), border: edge(ruleLine), ...press }),
  rule("staff-roster", { gap: 4, minHeight: 0, maxWidth: 390, pointerEvents: "auto" }),
  rule("staff-entity-button", { minHeight: 30, textAlign: "left", justifyContent: "start", backgroundColor: alpha(face, 0.86), border: edge(faceLine), ...press }),
  rule("staff-entity-button", { backgroundColor: alpha(teal, 0.2) }, "hover"),
  rule("staff-inspector", { minWidth: 360, width: 360, maxWidth: 360, flexShrink: 0, minHeight: 0, gap: 14, padding: 16, backgroundColor: alpha(surface, 0.98), border: edge(line), pointerEvents: "auto", overflow: "auto" }),
  rule("staff-inspector-heading", { flexDirection: "column", alignItems: "start", flexShrink: 0, gap: 4, paddingBottom: 10, borderBottom: edge(ruleLine) }),
  rule("staff-target-name", { color: bright, fontSize: 20, fontWeight: "bold", lineHeight: 1.15 }),
  rule("staff-inspector-tabs", { flexShrink: 0, gap: 2, flexWrap: "wrap" }),
  rule("staff-inspector-body", { minWidth: 0, minHeight: 0, gap: 14 }),
  rule("staff-target-summary", { gap: 6, padding: 12, backgroundColor: alpha(face, 0.55), border: edge(faceLine) }),
  rule("staff-target-heading", { flexWrap: "wrap" }),
  rule("staff-intervene", { gap: 5, padding: 6, backgroundColor: alpha(amber, 0.08), border: edge(alpha(amber, 0.55)) }),
  rule("staff-action-row", { flexWrap: "wrap", gap: 8 }),
  rule("staff-destructive", { paddingTop: 4, borderTop: edge(ruleLine) }),
  rule("staff-action-kill", { border: edge(redLine) }),
  rule("staff-action-delete", { border: edge(redLine) }),
  rule("staff-action-gib", { border: edge(redLine) }),
  rule("staff-profile", { gap: 4, padding: 6, backgroundColor: alpha(face, 0.55), border: edge(faceLine) }),
  rule("staff-profile-row", { minWidth: 0 }),
  rule("staff-profile-copy", { minWidth: 0, gap: 1 }),
  rule("staff-avatar-wrap", { flexShrink: 0 }),
  rule("staff-avatar", { width: 34, height: 34, minWidth: 34, flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center", color: teal, backgroundColor: alpha(screen, 0.8), border: edge(teal), borderRadius: 17, overflow: "hidden", fontFamily: "mono", fontSize: 10, fontWeight: "bold", textAlign: "center" }),
  rule("staff-avatar-portrait", { imageRendering: "pixelated" }),
  rule("staff-username", { color: bright, fontSize: 12, fontWeight: "bold" }),
  rule("staff-role", { color: dim, fontSize: 10 }),
  rule("staff-profile-context", { color: dim, fontSize: 10, lineHeight: 1.35 }),
  rule("staff-card-action", { alignSelf: "start", minHeight: 25, fontSize: 10 }),
  rule("staff-profile-hit", { justifyContent: "end", textAlign: "right", backgroundColor: "transparent", border: none }),
  rule("staff-profile-hit", { backgroundColor: "transparent", outline: edge(alpha(teal, 0.65)), outlineOffset: -1 }, "hover"),
  rule("staff-profile-hit", { backgroundColor: "transparent", outline: edge(teal, 2), outlineOffset: -2 }, "focus"),
  rule("staff-related-ref", { alignSelf: "start", textAlign: "left", ...press }),
  rule("staff-property", { minWidth: 0, flexDirection: "column", alignItems: "stretch", gap: 8, paddingTop: 10, paddingBottom: 10, borderBottom: edge(alpha(dim, 0.25)) }),
  rule("staff-property-control", { minWidth: 110, maxWidth: "100%", minHeight: 34 }),
  rule("field", { width: "100%", flexDirection: "column", alignItems: "stretch", gap: 4 }, { within: "staff-property" }),
  rule("staff-unit", { color: teal, fontSize: 10 }),
  rule("staff-current", { color: faint, fontSize: 10 }),
  rule("staff-audit-filter", { flexGrow: 0, minHeight: 28 }),
  rule("staff-audit-action", { color: bright, fontSize: 11 }),
  rule("staff-audit-row", { textAlign: "left", ...press }),
  rule("staff-spawn-drawer", { gap: 10, padding: 12, backgroundColor: alpha(face, 0.7), border: edge(amber) }),
  rule("staff-drawer-head", { justifyContent: "space-between" }),
  rule("staff-catalog-controls", { gap: 6, padding: 6, backgroundColor: alpha(surface, 0.6), border: edge(faceLine) }),
  rule("staff-catalog-search-row", { minWidth: 0, flexWrap: "wrap" }),
  rule("staff-catalog-search", { minWidth: 160, flexGrow: 1, minHeight: 34 }),
  rule("staff-catalog-more", { alignSelf: "start" }),
  rule("staff-coordinate-row", { flexWrap: "wrap", gap: 8 }),
  rule("staff-coordinate", { minWidth: 100, maxWidth: 120, minHeight: 34 }),
  rule("staff-cases-layout", { display: "flex", flexGrow: 1, minWidth: 0, minHeight: 0, gap: 7, alignItems: "stretch", backgroundColor: surface, pointerEvents: "auto" }),
  rule("staff-case-timeline", { flexGrow: 1, minWidth: 0, minHeight: 0, gap: 7, padding: 8, backgroundColor: surface, border: edge(line), overflow: "auto" }),
  rule("staff-case-rail", { minWidth: 200, width: 200, flexShrink: 0, minHeight: 0, gap: 6, padding: 8, backgroundColor: surface, border: edge(line), overflow: "auto" }),
  rule("staff-case-button", { minHeight: 34, textAlign: "left", justifyContent: "start", ...press }),
  rule("staff-case-filter", { width: "100%", flexGrow: 0 }),
  rule("staff-record-button", { minHeight: 29, textAlign: "left", justifyContent: "start", ...press }),
  rule("staff-timeline-heading", { flexShrink: 0, paddingBottom: 5, borderBottom: edge(ruleLine) }),
  rule("staff-evidence-chain", { gap: 5, padding: 7, backgroundColor: alpha(amber, 0.08), border: edge(alpha(amber, 0.55)) }),
  rule("staff-chain", { flexWrap: "wrap" }),
  rule("staff-chain-ref", { minHeight: 28, ...press }),
  rule("staff-filter-banner", { padding: 4, backgroundColor: alpha(amber, 0.12), border: edge(amber) }),
  rule("staff-event-time", { minWidth: 72, fontFamily: "mono", textAlign: "left", ...press }),
  rule("staff-event-action", { color: bright, fontSize: 11 }),
  rule("staff-event-actor", { color: ink, fontSize: 11 }),
  rule("staff-evidence-inspector", { minWidth: 360, width: 360, maxWidth: 360, flexShrink: 0, minHeight: 0, gap: 14, padding: 16, backgroundColor: surface, border: edge(line), overflow: "auto" }),
  rule("staff-profile-inspector", { gap: 5 }),
  rule("staff-entity-inspector", { gap: 4 }),
  rule("staff-event-inspector", { gap: 4 }),
  rule("staff-warning", { padding: 5, color: amber, border: edge(alpha(amber, 0.5)), fontSize: 11 }),
  rule("staff-outcome", { gap: 6, padding: 7, backgroundColor: alpha(face, 0.65), border: edge(faceLine) }),
  rule("staff-review-target", { color: bright, fontSize: 13, fontWeight: "bold" }),
  rule("staff-review-target", { outline: edge(red), outlineOffset: -1 }, "focus"),
  rule("staff-map-marker", { minHeight: 24, backgroundColor: alpha(face, 0.92), border: edge(teal), color: bright, ...press }),
  rule("screen-footer", { flexShrink: 0, minHeight: 28, maxHeight: 28, padding: 5, borderTop: edge(ruleLine), backgroundColor: alpha(surface, 0.96), pointerEvents: "auto" }, { within: "staff-shell" }),
];

/** Staff package sheet includes the shared control geometry explicitly. */
export default defineStyles([...kitRules, ...staffRules] as UiStyleRule[]);
