// The surfaces a document opens in: the host window's own parts, a
// document's head strip and body, the readout hierarchy inside it, the
// action strip and the status line. Appended to `hudRules`.
import { rule } from "@lunatic/ui";
import { edge, face, faceLine, flat, ink, none, outline, teal, titleFace, titleLine } from "./theme-tokens";

export const docRules = [
  // Host window parts: the title strip the pack may paint, and a body
  // whose padding belongs to the document drawn inside it.
  rule("window-title", {
    minHeight: 34,
    alignItems: "center",
    paddingLeft: 9,
    paddingRight: 9,
    backgroundColor: titleFace,
    borderBottom: edge(titleLine),
    fontFamily: "mono",
    fontSize: 11,
    letterSpacing: 1,
    color: "#d5e3d9",
  }),
  rule("window-body", { padding: 0, overflow: "auto" }),

  // A document window: a head strip that reads as part of the title bar.
  rule("doc-pane", {
    padding: 0,
    gap: 0,
    maxWidth: "100%",
    backgroundColor: "#132226",
    border: edge("#607d78"),
    borderRadius: 5,
    overflow: "hidden",
  }),
  rule("doc-head", {
    height: 34,
    alignItems: "center",
    justifyContent: "end",
    paddingLeft: 9,
    paddingRight: 9,
    backgroundColor: titleFace,
    borderBottom: edge("#3d564d"),
  }),
  rule("doc-close", {
    width: 26,
    minWidth: 26,
    height: 25,
    padding: 0,
    fontFamily: "mono",
    fontSize: 17,
    color: "#d2e0d5",
    backgroundColor: "#15262b",
    border: edge("#668078"),
    borderRadius: 3,
  }),
  rule("doc-close", { backgroundColor: "#385458" }, "hover"),
  rule("doc-body", { padding: 16, gap: 6 }),

  // A module readout: eyebrow, heading, stat blocks, then its rows.
  rule("mod-eyebrow", {
    justifyContent: "space-between",
    gap: 8,
    fontFamily: "mono",
    fontSize: 8,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#92aaa0",
  }),
  rule("mod-head", {
    fontSize: 17,
    fontWeight: "normal",
    lineHeight: 1.2,
    color: ink,
    marginTop: 14,
    marginBottom: 14,
  }),
  rule("mod-stats", { gap: 25, flexWrap: "wrap", marginBottom: 4 }),
  rule("mod-stat", { gap: 7, minWidth: 0 }),
  rule("mod-stat-label", {
    fontFamily: "mono",
    fontSize: 8,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#9aafa4",
  }),
  rule("mod-stat-value", {
    fontFamily: "mono",
    fontSize: 23,
    fontWeight: "bold",
    lineHeight: 1,
    color: "#d1e1d1",
  }),
  rule("mod-unit", { fontSize: 10, color: "#9db9a7", fontStyle: "normal" }),
  rule("gauge", {
    height: 6,
    marginTop: 12,
    marginBottom: 4,
    backgroundColor: "#0e1b1d",
    border: edge("#38564e"),
    borderRadius: 0,
    accentColor: "#83ad93",
  }),
  rule("module-row", {
    alignItems: "center",
    justifyContent: "space-between",
    gap: 15,
    marginTop: 8,
    fontSize: 11,
  }),
  rule("mod-pill", {
    minWidth: 64,
    fontSize: 9,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 13,
    paddingRight: 13,
    borderRadius: 2,
    color: ink,
    backgroundColor: face,
    border: edge(faceLine),
  }),
  rule("mod-foot", {
    justifyContent: "space-between",
    gap: 8,
    borderTop: edge("#3d564d"),
    paddingTop: 11,
    marginTop: 13,
    fontFamily: "mono",
    fontSize: 8,
    fontStyle: "normal",
    color: "#819e91",
  }),

  // The action strip, centred on the same origin as the hands.
  rule("action-strip", {
    position: "absolute",
    left: 0,
    bottom: 228,
    width: 0,
    alignItems: "end",
    justifyContent: "center",
    gap: 9,
    pointerEvents: "none",
  }),
  rule("action-group", {
    position: "relative",
    flexShrink: 0,
    paddingTop: 11,
    gap: 4,
    alignItems: "end",
  }),
  rule("group-label", {
    position: "absolute",
    left: 1,
    top: 0,
    fontFamily: "mono",
    fontSize: 7,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#c0cfc0",
    textShadow: outline,
  }),
  rule("ability", {
    width: 34,
    height: 34,
    minWidth: 34,
    padding: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#26383adf",
    border: edge("#61766b"),
    borderRadius: 2,
    overflow: "hidden",
  }),
  rule("ability", { backgroundColor: "#3d5745df" }, "hover"),
  rule("ability-icon", { width: 24, height: 24 }),
  rule("action-button", {
    height: 34,
    minWidth: 44,
    fontSize: 8,
    paddingLeft: 6,
    paddingRight: 6,
    backgroundColor: face,
    border: edge(faceLine),
    borderRadius: 2,
  }),

  // The top-right status: where this body is, and who it is.
  rule("statusline", {
    alignItems: "center",
    gap: 8,
    padding: 0,
    backgroundColor: "transparent",
    border: none,
    borderRadius: 0,
    boxShadow: flat,
    fontFamily: "mono",
    fontSize: 11,
    color: "#d6dfd2",
    textShadow: outline,
    pointerEvents: "none",
  }),
  rule("statusdot", {
    width: 5,
    height: 5,
    flexShrink: 0,
    backgroundColor: teal,
    borderRadius: 0,
  }),
  rule("statusname", {
    marginLeft: 3,
    paddingLeft: 11,
    borderLeft: edge("#697b74"),
    fontFamily: "mono",
    fontSize: 11,
    color: "#a4b5af",
    textShadow: outline,
  }),
];

