import assert from 'node:assert/strict';

export async function checkConcept(ui) {
  const { call, evaluate, rect, click, drag, screenshot, settle } = ui;
  const state = () => evaluate('JSON.parse(JSON.stringify(TerminalConcept.state))');
  const key = async (key, code, windowsVirtualKeyCode, modifiers = 0) => {
    for (const type of ['keyDown', 'keyUp']) await call('Input.dispatchKeyEvent', { type, key, code, windowsVirtualKeyCode, modifiers });
    await settle();
  };
  const replaceText = async text => {
    await click('#file-view textarea');
    await key('a', 'KeyA', 65, 2);
    await call('Input.insertText', { text });
  };
  const reset = async options => {
    await evaluate(`TerminalConcept.reset(${JSON.stringify(options || {})}); TerminalInteractions.reset()`);
    await settle();
  };
  const sameRect = (a, b) => {
    for (const key of ['x', 'y', 'width', 'height']) assert.ok(Math.abs(a[key] - b[key]) < 1, `Window ${key} changed`);
  };
  const clickText = async text => {
    const selector = await evaluate(`(() => { const b = [...document.querySelectorAll('#file-view button')].find(b => b.textContent.trim() === ${JSON.stringify(text)}); if (!b) throw Error('Missing button'); b.dataset.captureTarget = 'true'; return '[data-capture-target="true"]'; })()`);
    await click(selector);
    await evaluate('document.querySelectorAll("[data-capture-target]").forEach(n => delete n.dataset.captureTarget)');
  };
  const withinViewport = async () => {
    const bounds = await rect('#terminal');
    const viewport = await evaluate('({width:innerWidth,height:innerHeight})');
    assert.ok(bounds.x >= 0 && bounds.y >= 0, 'Window starts inside viewport');
    assert.ok(bounds.x + bounds.width <= viewport.width + 1, 'Window fits viewport width');
    assert.ok(bounds.y + bounds.height <= viewport.height + 1, 'Window fits viewport height');
    const file = await rect('#file-view');
    assert.ok(file.width >= 300 && file.height >= 200, 'File viewer remains usable');
    assert.equal(await evaluate('document.documentElement.scrollWidth > innerWidth'), false, 'No page overflow');
  };
  await reset();
  await evaluate('Promise.all([...document.querySelectorAll("#terminal img")].map(image => image.decode()))');
  assert.equal(await evaluate(`[...document.querySelectorAll('#terminal img')].every(image => {
    const style = getComputedStyle(image);
    return image.naturalWidth === 32 && image.naturalHeight === 32 && style.width === '32px' && style.height === '32px' && style.imageRendering === 'pixelated';
  }) && document.querySelectorAll('#terminal img').length === 9`), true, 'Terminal uses nine native 32px pixelated raster icons');
  assert.equal(await evaluate('document.querySelectorAll("#computer-status img").length'), 0, 'Computer status has no redundant machine image');
  assert.equal(await evaluate(`[...document.querySelectorAll('#terminal-title img')].filter(image => image.getAttribute('src') === 'sprites/computer.png').length`), 1, 'Title bar has exactly one computer image');
  assert.equal(await evaluate(`[...document.querySelectorAll('#terminal img')].filter(image => image.getAttribute('src') === 'sprites/computer.png' && image.getBoundingClientRect().width > 0 && image.getBoundingClientRect().height > 0).length`), 1, 'Terminal has exactly one visible computer image');
  assert.equal(await evaluate(`[...document.querySelectorAll('.computer-icon, .tv-file-icon')].every(icon =>
    icon.tagName === 'IMG' && ['::before', '::after'].every(pseudo => ['none', 'normal'].includes(getComputedStyle(icon, pseudo).content)))`), true, 'Computer/file icons contain no CSS pseudo artwork');
  const rasterNames = await evaluate(`[...new Set([...document.querySelectorAll('#terminal img')].map(image => image.getAttribute('src').split('/').pop()))].sort()`);
  assert.deepEqual(rasterNames, ['computer.png', 'file-atmo.png', 'file-disl.png', 'file-md.png', 'file-pem.png'], 'Computer and all four file types use correct raster family');
  assert.equal(await evaluate(`[...document.querySelectorAll('#drive-b button')].find(button => button.textContent.includes('Eject'))?.textContent.trim()`), '⏏ Eject disk', 'Eject retains requested Unicode glyph');
  assert.equal(await evaluate(`[...document.querySelectorAll('#drive-b button')].find(button => button.textContent.includes('Eject')).querySelector('img') === null`), true, 'Eject contains no raster image');
  await screenshot('source-with-floppy');
  await click('[data-file-id="disk:access"]');
  let credential = (await state()).files.find(f => f.id === 'disk:access');
  assert.equal((await state()).selected, 'disk:access', 'B credential opens in file viewer');
  assert.equal(credential.name, 'engineering_access.pem');
  assert.equal(credential.type, 'pem');
  assert.ok(await evaluate('document.querySelector("#file-view").textContent.includes("ACCESS MATERIAL")'), 'Credential has access material heading');
  assert.ok(await evaluate('document.querySelector("#file-view textarea").value.startsWith("-----BEGIN FICTIONAL STATION CREDENTIAL-----")'), 'Credential displays explicitly fictional plain text');
  assert.equal(await evaluate('[...document.querySelectorAll("#file-view button")].some(b => ["Preview", "Readout"].includes(b.textContent.trim()))'), false, 'Credential remains a plain text editor');
  await screenshot('credential');
  await click('#file-view textarea');
  await call('Input.insertText', { text: 'CDP_CREDENTIAL_EDIT\n' });
  await click('[data-save]');
  credential = (await state()).files.find(f => f.id === 'disk:access');
  assert.equal(credential.dirty, false, 'Credential edit saves');
  assert.ok(credential.savedBody.includes('CDP_CREDENTIAL_EDIT'), 'Credential saves edited plain text');
  await click('#demo-source');
  await click('[data-file-id="disk:access"]');
  assert.ok(await evaluate('document.querySelector("#file-view textarea").value.includes("CDP_CREDENTIAL_EDIT")'), 'Reopened credential retains saved text');
  await reset();
  const original = await rect('#terminal');
  await drag('#terminal-title', 31, 25);
  const moved = await rect('#terminal');
  assert.ok(moved.x > original.x + 10 && moved.y > original.y + 10, 'Window title drag moves window');
  await withinViewport();
  await reset();
  const sizeBefore = await rect('#terminal');
  await drag('[data-resize="se"]', 55, 30);
  const sizeAfter = await rect('#terminal');
  assert.ok(sizeAfter.width > sizeBefore.width + 20 && sizeAfter.height > sizeBefore.height + 10, 'Corner resize expands window');
  await withinViewport();
  await reset();
  const aBefore = await rect('#drive-a');
  const windowBefore = await rect('#terminal');
  await drag('#split-a', 37, 0);
  assert.ok((await rect('#drive-a')).width > aBefore.width + 15, 'A splitter changes A width');
  sameRect(windowBefore, await rect('#terminal'));
  const bBefore = await rect('#drive-b');
  await drag('#split-b', 31, 0);
  assert.ok(Math.abs((await rect('#drive-b')).width - bBefore.width) > 10, 'B splitter changes B width');
  sameRect(windowBefore, await rect('#terminal'));
  await reset();
  await drag('#split-a', 130, 0);
  await drag('#split-b', -130, 0);
  const wide = await rect('#terminal');
  await drag('[data-resize="e"]', 740 - wide.width, 0);
  assert.ok(Math.abs((await rect('#terminal')).width - 740) < 1, 'Window shrinks to minimum width');
  const narrowFrames = await rect('#frames'), narrowB = await rect('#drive-b');
  assert.ok(narrowB.x + narrowB.width <= narrowFrames.x + narrowFrames.width + 1, 'B remains inside frames after shrinking wide columns');
  assert.ok((await rect('#file-view')).width >= 280, 'Minimum window retains 280px editor');
  await reset();
  await click('[data-file-id="disk:backup"]');
  assert.equal((await state()).selected, 'disk:backup', 'B entry opens B file');
  assert.ok(await evaluate('document.querySelector("#file-view").textContent.includes("filter_backup.disl")'), 'Viewer names B file');
  await click('[data-file-id="host:filter"]');
  assert.equal((await state()).selected, 'host:filter', 'A entry opens A file');
  await click('#file-view textarea');
  await call('Input.insertText', { text: '-- CDP verified edit\n' });
  assert.equal((await state()).files.find(f => f.id === 'host:filter').dirty, true, 'Trusted input marks source dirty');
  await click('[data-file-id="disk:notes"]');
  assert.equal(await evaluate('document.querySelector("#dialog-backdrop").hidden'), false, 'Dirty switch asks to save');
  assert.equal(await evaluate('document.querySelector("#terminal").inert'), true, 'Modal makes terminal inert');
  assert.equal(await evaluate('document.querySelector("#demo-source").closest("[inert]") !== null'), true, 'Modal makes gallery inert');
  for (let i = 0; i < 5; i++) {
    await key('Tab', 'Tab', 9);
    assert.equal(await evaluate('!!document.activeElement.closest("#dialog-backdrop")'), true, 'Tab stays within dialog');
  }
  for (let i = 0; i < 5; i++) {
    await key('Tab', 'Tab', 9, 8);
    assert.equal(await evaluate('!!document.activeElement.closest("#dialog-backdrop")'), true, 'Shift+Tab stays within dialog');
  }
  await screenshot('dirty-confirmation');
  await click('#dialog-actions button:last-child');
  assert.equal((await state()).selected, 'host:filter', 'Cancel retains file');
  await click('[data-file-id="disk:notes"]');
  await click('#dialog-actions button:first-child');
  assert.equal((await state()).selected, 'disk:notes', 'Save completes pending file selection');
  const saved = (await state()).files.find(f => f.id === 'host:filter');
  assert.equal(saved.dirty, false);
  assert.ok(saved.savedBody.includes('-- CDP verified edit'), 'Dirty guard saves edited source');
  await reset();
  const beforeEject = await rect('#terminal');
  const viewBeforeEject = await rect('#file-view');
  await click('#demo-disk');
  assert.equal((await state()).disk, false);
  assert.equal(await evaluate('document.querySelector("#drive-b").hidden'), true);
  assert.equal(await evaluate('document.querySelector("#split-b").hidden'), true);
  sameRect(beforeEject, await rect('#terminal'));
  assert.ok((await rect('#file-view')).width > viewBeforeEject.width + 50, 'Viewer takes removed B column space');
  assert.equal(await evaluate('[...document.querySelectorAll("#drive-a button")].find(b => b.textContent.includes("Copy"))?.disabled'), true, 'No cross-drive copy without inserted media');
  await screenshot('source-local-only');
  await click('#demo-disk');
  assert.equal((await state()).disk, true, 'Disk inserts again');
  sameRect(beforeEject, await rect('#terminal'));
  await click('[data-file-id="disk:backup"]');
  await click('#demo-disk');
  assert.equal((await state()).selected, 'host:filter', 'Ejecting selected B file selects local file');
  await reset();
  await click('#demo-document');
  assert.equal((await state()).selected, 'host:readme');
  assert.equal((await state()).files.find(f => f.id === 'host:readme').name, 'readme.md', 'Markdown uses .md filename');
  assert.equal((await state()).files.find(f => f.id === 'host:readme').type, 'md', 'Markdown uses md type');
  assert.equal((await state()).files.some(f => f.name.endsWith('.doc') || f.type === 'doc'), false, 'No legacy document extension remains');
  assert.ok(await evaluate('!!document.querySelector("#file-view h1")'), 'Markdown renders a heading');
  await screenshot('markdown');
  await clickText('Edit');
  await click('#file-view textarea');
  await call('Input.insertText', { text: 'Verified document edit ' });
  await click('[data-save]');
  await clickText('Preview');
  assert.ok(await evaluate('document.querySelector(".tv-document").textContent.includes("Verified document edit")'), 'Markdown preview reflects saved edit');
  await clickText('Edit');
  await click('#file-view textarea');
  await call('Input.insertText', { text: 'UNSAVED_PREVIEW_MARKER ' });
  await clickText('Preview');
  assert.ok(await evaluate('document.querySelector(".tv-document").textContent.includes("UNSAVED_PREVIEW_MARKER")'), 'Preview displays dirty document');
  await click('[data-revert]');
  assert.equal(await evaluate('document.querySelector(".tv-document").textContent.includes("UNSAVED_PREVIEW_MARKER")'), false, 'Revert refreshes preview to saved text');
  assert.ok(await evaluate('document.querySelector(".tv-document").textContent.includes("Verified document edit")'), 'Reverted preview retains saved document');
  await reset();
  await click('#demo-record');
  assert.equal((await state()).selected, 'host:atmos');
  await screenshot('record');
  await clickText('Source');
  await click('#file-view textarea');
  await call('Input.dispatchKeyEvent', { type: 'keyDown', key: 'a', code: 'KeyA', windowsVirtualKeyCode: 65, modifiers: 2 });
  await call('Input.dispatchKeyEvent', { type: 'keyUp', key: 'a', code: 'KeyA', windowsVirtualKeyCode: 65, modifiers: 2 });
  await call('Input.insertText', { text: '{"label":"CAPTURE VERIFIED","pressure_kpa":98.7,"temperature_k":294.2,"filter":"CO2","enabled":true}' });
  await click('[data-save]');
  await clickText('Readout');
  assert.ok(await evaluate('document.querySelector(".tv-atmo").textContent.includes("98.7")'), 'Custom record readout reflects saved data');
  await clickText('Source');
  await replaceText('{"history":1,"readings":[null]}');
  await click('[data-save]');
  await clickText('Readout');
  assert.ok(await evaluate('!!document.querySelector(".tv-atmo")'), 'Malformed optional record fields render without exception');
  await reset();
  await replaceText('-- SYNTAX_ERROR');
  await click('[data-save]');
  assert.ok(await evaluate('document.querySelector("[data-diagnostic]").textContent.includes("SYNTAX_ERROR")'), 'Failed source save displays diagnostic');
  assert.ok((await rect('[data-diagnostic]')).height > 0, 'Diagnostic is visible');
  assert.equal((await state()).files.find(f => f.id === 'host:filter').dirty, true, 'Failed save retains unsaved source');
  await replaceText('-- Valid source after diagnostic');
  const revision = (await state()).files.find(f => f.id === 'host:filter').revision;
  await key('s', 'KeyS', 83, 2);
  assert.equal((await state()).files.find(f => f.id === 'host:filter').revision, revision + 1, 'Ctrl+S saves exactly once');
  await click('#file-view textarea');
  await key('Tab', 'Tab', 9, 8);
  assert.equal(await evaluate('document.activeElement.matches("textarea")'), false, 'Shift+Tab exits editor');
  await reset();
  await click('#terminal-close');
  assert.equal(await evaluate('document.querySelector("#terminal").hidden'), true, 'Close hides window');
  await click('#terminal-restore');
  assert.equal(await evaluate('document.querySelector("#terminal").hidden'), false, 'Restore reopens window');
  const beforeMaximize = await rect('#terminal');
  await click('#terminal-maximize');
  assert.ok((await rect('#terminal')).width > beforeMaximize.width, 'Maximize enlarges window');
  await withinViewport();
  await click('#terminal-maximize');
  sameRect(beforeMaximize, await rect('#terminal'));
  await call('Emulation.setDeviceMetricsOverride', { width: 1366, height: 768, deviceScaleFactor: 1, mobile: false });
  await reset();
  await withinViewport();
  await screenshot('compact-source-with-floppy');
  await click('[data-file-id="disk:access"]');
  await screenshot('compact-credential');
  await click('#demo-source');
  await click('#demo-disk');
  await withinViewport();
  await screenshot('compact-source-local-only');
  await click('#demo-document');
  await screenshot('compact-markdown');
  await click('#demo-record');
  await screenshot('compact-record');
  await reset();
  await click('#file-view textarea');
  await call('Input.insertText', { text: '-- Pending adjustment\n' });
  await click('#demo-document');
  await screenshot('compact-dirty-confirmation');
  console.log('PASS: drive selection, splitters, drag, dirty Save/Cancel, eject/insert, Markdown, record, close/reopen, compact layout');
}
